Need to fix the following error:
Severity Code Description Project File Line Suppression State
Error C2675 unary '++': '_OutIt' does not define this operator or a conversion to a type acceptable to the predefined operator SOS C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\algorithm 2673